# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'pg'

development:
  adapter: postgresql
  encoding: unicode
  database: question_services_development
  pool: 5
  username: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: question_services_test
  pool: 5
  username: postgres
  host: localhost

production:
  adapter: postgresql
  database: question_services_production
  encoding: unicode
  pool: 5
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost